[project]
name = "order-dispatch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Arun/nexus", email = "mspaayal05@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
order-dispatch = "order_dispatch:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
