from mongodb.mongodb_connection import mongodbclient
from logger import logging
from datetime import datetime, timezone
import uuid


class assembly_manager(mongodbclient):

    def __init__(self, product_name=None, product_id=None, model_number=None, quantity=None,
                 parts_used=None, serials=None, created_by=None):
        """
        product_name / product_id / model_number: what is being assembled
        quantity: int -> how many units of this product are being built in this batch
        parts_used: list of dicts, one per part consumed to build this batch ->
            {
                "part_name": str,
                "quantity": int,                    # total used for the whole batch
                "source": "inventory" | "local",     # "inventory" -> deducted from inventory's
                                                      # spare_parts stock; "local" -> sourced
                                                      # outside, never touches inventory
            }
        serials: list of dicts, one per assembled unit ->
            {"serial_number": str, "hologram_number": str}
            serial_number is entered/generated by the caller; hologram_number is
            filled in server-side (app.py create_assembly) from the hologram
            numbers already on file for the inventory part used to build this
            batch — never entered by hand.
        created_by: str -> username of the admin/employee who logged the assembly
        """

        super().__init__()

        self.assembly_id = str(uuid.uuid4())
        self.product_name = product_name
        self.product_id = product_id
        self.model_number = model_number
        self.quantity = quantity or 0
        self.parts_used = parts_used or []
        self.serials = serials or []
        self.created_by = created_by

    @staticmethod
    def _normalize_parts_used(parts_used):
        normalized = []
        for part in parts_used:
            part_name = (part.get("part_name") or "").strip()
            if not part_name:
                continue
            source = part.get("source", "inventory")
            if source not in ("inventory", "local"):
                source = "inventory"
            normalized.append({
                "part_name": part_name,
                "quantity": part.get("quantity", 0) or 0,
                "source": source,
            })
        return normalized

    @staticmethod
    def _normalize_serials(serials):
        normalized = []
        for s in serials:
            entry = {
                "serial_number": (s.get("serial_number") or "").strip(),
                "hologram_number": (s.get("hologram_number") or "").strip(),
            }
            if s.get("replaced"):
                entry["replaced"] = True
                entry["previous_hologram_number"] = s.get("previous_hologram_number", "")
            normalized.append(entry)
        return normalized

    def add(self, collection_name):
        try:
            if not self.product_name:
                raise Exception("assembly must have a product name")
            if not self.quantity or self.quantity <= 0:
                raise Exception("assembly quantity must be greater than 0")

            parts_used = self._normalize_parts_used(self.parts_used)
            serials = self._normalize_serials(self.serials)

            if len(serials) != self.quantity:
                raise Exception("number of serial/hologram entries must match the assembly quantity")
            if any(not s["serial_number"] or not s["hologram_number"] for s in serials):
                raise Exception("every unit needs both a serial number and a hologram number")

            serial_values = [s["serial_number"] for s in serials]
            hologram_values = [s["hologram_number"] for s in serials]
            if len(set(serial_values)) != len(serial_values):
                raise Exception("serial numbers must be unique within this batch")
            if len(set(hologram_values)) != len(hologram_values):
                raise Exception("hologram numbers must be unique within this batch")

            assembly_dict = {
                "assembly_id": self.assembly_id,
                "product_name": self.product_name,
                "product_id": self.product_id,
                "model_number": self.model_number,
                "quantity": self.quantity,
                "parts_used": parts_used,
                "serials": serials,
                "status": "pending",           # flips to "completed" via mark_completed()
                "created_by": self.created_by,
                "created_at": datetime.now(timezone.utc).isoformat(),
            }
            result = super().add(collection_name=collection_name, dictionary=assembly_dict)
            return result, self.assembly_id

        except Exception as e:
            logging.error("adding assembly failed!")
            raise Exception(e)

    def get_data(self, collection_name, query=None, projection=None):
        try:
            dataset = super().get_data(collection_name, query, projection)
            return dataset
        except Exception as e:
            logging.error("assembly data fetching was failed!")
            raise Exception(e)

    def delete(self, collection_name, query, many=False):
        try:
            deleted_assembly = super().delete_data(collection_name=collection_name, query=query, many=many)
            return deleted_assembly
        except Exception as e:
            logging.error("assembly deletion was not successful")
            raise Exception(e)

    def update(self, collection_name, query, update_values, many=False):
        try:
            if "parts_used" in update_values:
                update_values["parts_used"] = self._normalize_parts_used(update_values["parts_used"])
            if "serials" in update_values:
                update_values["serials"] = self._normalize_serials(update_values["serials"])
            updated_data = super().update_data(collection_name=collection_name, query=query, update_values=update_values, many=many)
            return updated_data
        except Exception as e:
            logging.error("assembly updation was failed!")
            raise Exception(e)

    def mark_completed(self, collection_name, assembly_id):
        try:
            result = self.update(
                collection_name=collection_name,
                query={"assembly_id": assembly_id},
                update_values={"status": "completed"},
            )
            logging.info(f"assembly {assembly_id} marked as completed")
            return result
        except Exception as e:
            logging.error("marking assembly as completed failed!")
            raise Exception(e)

    def assembly_tracking(self, collection_name: str, assembly_id):
        try:
            dataset = self.get_data(collection_name=collection_name, query={"assembly_id": assembly_id})
            if not dataset:
                raise Exception(f"no assembly found with id {assembly_id}")
            return dataset[0]
        except Exception as e:
            logging.error("assembly tracking failed!")
            raise Exception(e)